(define (problem aloca-pessoas-no-hotel)
    (:domain hotel)
    (:requirements :universal-preconditions)
    (:objects Casimiro Igor DavyJones Iasmine Chris - person
              Bruno&Rose Otaviano&Vanessa - couple
              room0 room1 room2 room3 room4 room5 room6 room7 room8 room9 - room
    )
    (:init
           (not (allocated Casimiro))
           (male Casimiro)
           (not (allocated Igor))
           (male Igor)
           (not (allocated DavyJones))
           (male DavyJones)
           (not (allocated Iasmine))
           (female Iasmine)
           (not (allocated Chris))
           (female Chris)
           (not (allocated-couple Bruno&Rose))
           (not (allocated-couple Otaviano&Vanessa))
           (is-available room0)
           (couple-room room0)
           (= (price room0) 100)
           (is-available room1)
           (couple-room room1)
           (= (price room1) 150)
           (is-available room2)
           (couple-room room2)
           (= (price room2) 1000)
           (is-available room3)
           (double-room room3)
           (= (price room3) 150)
           (is-available room4)
           (double-room room4)
           (= (price room4) 200)
           (is-available room5)
           (triple-room room5)
           (= (price room5) 250)
           (is-available room6)
           (triple-room room6)
           (= (price room6) 600)
           (is-available room7)
           (triple-room room7)
           (= (price room7) 250)
           (is-available room8)
           (quadruple-room room8)
           (= (price room8) 360)
           (is-available room9)
           (quadruple-room room9)
           (= (price room9) 990)
           (= (total-cost) 0)
    )
    (:goal
      (and (forall (?person - person) (and(allocated ?person)))
           (forall (?couple - couple) (and(allocated-couple ?couple)))
      )
    )
    (:metric minimize (total-cost))
)